site_name: QAT Documentation
site_url: https://qir-alliance.github.io/qat/
base_url: /
docs_dir: src
site_description: Everything you need to know about QAT API.
site_author: troels

plugins:
  - search

theme:
  name: null
  custom_dir: "tailwind_theme/"
  theme_dir: "tailwind_theme/"
  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: false

  highlightjs: true
  hljs_languages: []
  hljs_style: "monokai-sublime"

  navigation_depth: 2
  nav_style: primary

  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s

nav:
  - User guide:
    - Quick start: "UserGuide/QuickStart.md"
    - Building the library: "UserGuide/BuildingLibrary.md"
    - Introduction to profiles: "UserGuide/IntroductionToProfiles.md"
    - Applying a profile (TODO(issue-8): Yet to be written)

  - Developer guide:
    - Architecture Overview: "DeveloperGuide/ArchitectureOverview.md"
    - Writing a Component: "DeveloperGuide/WritingComponent.md"
    - Configuration Library: "DeveloperGuide/ConfigurationLibrary.md"
    - Rule based extensions: "DeveloperGuide/WritingRuleTests.md"
    - API: "api.md"

  - Contributing:
    - Code quality: "DeveloperGuide/CodeQuality.md"
    - Developer FAQ: "DeveloperGuide/DeveloperFAQ.md"    