name: Linux CI

on:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Installing dependencies"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y 
          sudo apt-get remove -y llvm-12
          sudo apt-get install -y curl pkg-config findutils  wget
          sudo apt install -y clang-11 cmake clang-format-11 clang-tidy-11 
          sudo apt-get install -y llvm-11 lldb-11 llvm-11-dev libllvm11 llvm-11-runtime
          sudo apt install -y python3 python3-pip 
          sudo apt-get remove -y llvm-10
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 0
          git submodule update --init --recursive
          pip install -r requirements.txt  
          chmod +x manage
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Checking format"
        run: |
          ./manage stylecheck        
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Running unit tests"
        run: |
          ./manage test
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11

      - name: "Performing static analysis"
        run: |
          ./manage lint
        env:
          DEBIAN_FRONTEND: noninteractive
          PYTHONUNBUFFERED: 1
          PYTHON_BIN_PATH: /usr/bin/python3
          CC: clang-11
          CXX: clang++-11
